# Generated by Django 4.1.2 on 2023-11-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_delete_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listing',
            field=models.ManyToManyField(related_name='watched_listings', to='auctions.listing'),
        ),
    ]
